let list=JSON.parse(localStorage.getItem("jc_products")||"null")||PRODUCTS;
const $=id=>document.getElementById(id);
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
let editId=null;

function persist(){localStorage.setItem("jc_products",JSON.stringify(list));}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}

function render(){
  $("count").textContent=`${list.length} product${list.length===1?"":"s"}`;
  $("list").innerHTML=list.length?list.map(p=>`<div class="row">
    <img src="${esc(p.image)}" onerror="this.style.opacity=.15">
    <div><b>${esc(p.name)}</b><small>${esc(p.category)} • ${money(p.price)}${p.oldPrice?` • MRP ${money(p.oldPrice)}`:""}</small></div>
    <button class="btn small" onclick="edit(${p.id})">Edit</button><button class="btn small danger" onclick="removeProduct(${p.id})">Delete</button>
  </div>`).join(""):`<p class="empty">No products yet.</p>`;
}
function clearForm(){
  $("form").reset();$("id").value="";$("formTitle").textContent="Add Product";$("cancel").hidden=true;editId=null;
}
function edit(id){
  const p=list.find(x=>x.id===id);if(!p)return;editId=id;
  $("id").value=p.id;$("name").value=p.name;$("category").value=p.category;$("price").value=p.price;
  $("oldPrice").value=p.oldPrice||"";$("badge").value=p.badge||"";$("image").value=p.image;$("description").value=p.description||"";
  $("details").value=(p.details||[]).join(", ");$("featured").checked=!!p.featured;
  $("formTitle").textContent="Edit Product";$("cancel").hidden=false;scrollTo({top:0,behavior:"smooth"});
}
function removeProduct(id){
  if(!confirm("Delete this product?"))return;
  list=list.filter(p=>p.id!==id);persist();render();
}
function formProduct(){
  return {id:editId||Date.now(),name:$("name").value.trim(),category:$("category").value.trim(),price:+$("price").value,oldPrice:+$("oldPrice").value||0,
    badge:$("badge").value.trim(),image:$("image").value.trim(),description:$("description").value.trim(),
    details:$("details").value.split(",").map(x=>x.trim()).filter(Boolean),featured:$("featured").checked};
}
$("form").onsubmit=e=>{e.preventDefault();const p=formProduct();if(editId)list=list.map(x=>x.id===editId?p:x);else list.push(p);persist();render();clearForm();alert("Product saved in this browser.");};
$("cancel").onclick=clearForm;
$("reset").onclick=()=>{if(confirm("Restore the four demo products?")){list=PRODUCTS.map(x=>({...x}));persist();render();}};
function generated(){
  return `/* Generated by Jignesh Collection Product Manager */\nconst STORE_CONFIG = ${JSON.stringify(STORE_CONFIG,null,2)};\n\nconst PRODUCTS = ${JSON.stringify(list,null,2)};\n`;
}
$("download").onclick=()=>{const blob=new Blob([generated()],{type:"text/javascript"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="products.js";a.click();URL.revokeObjectURL(a.href)};
$("copy").onclick=async()=>{try{await navigator.clipboard.writeText(generated());alert("products.js copied.");}catch(e){alert("Copy failed. Use Download instead.")}};
render();
